# -*- coding: utf-8 -*-
"""Smart Building Digital Twin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9RcECwPblNIjqPYH451f-o1DYcY0Aux
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

url = "https://raw.githubusercontent.com/ideas-lab-nus/robod/master/Data/combined_Room1.csv"

df = pd.read_csv(url)

df.shape

df.columns

selected_columns = [
    "timestamp",
    "air_temperature",
    "indoor_relative_humidity",
    "indoor_co2",
    "illuminance",
    "occupant_count",
    "ceiling_fan_energy",
    "lighting_energy",
    "plug_load_energy",
    "chilled_water_energy",
    "fcu_fan_energy",
    "outdoor_relative_humidity",
    "dry_bulb_temp"
]

df_project = df[selected_columns].copy()

df_project.shape

df_project.head()

df_project.isnull().sum()

df_project["timestamp"] = pd.to_datetime(
    df_project["timestamp"],
    errors="coerce"
)

df_project.head()

df_project.info()

df_project = df_project.ffill()

df_project.isnull().sum()

df_project["hour"] = df_project["timestamp"].dt.hour
df_project["day_of_week"] = df_project["timestamp"].dt.day_name()
df_project["month"] = df_project["timestamp"].dt.month

df_project.head()

df_project.describe()

plt.figure(figsize=(12, 5))

plt.plot(
    df_project["timestamp"],
    df_project["lighting_energy"]
    + df_project["plug_load_energy"]
    + df_project["chilled_water_energy"]
    + df_project["fcu_fan_energy"]
    + df_project["ceiling_fan_energy"]
)

plt.xlabel("Time")
plt.ylabel("Energy Consumption")
plt.title("Building Energy Consumption Over Time")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df_project["total_energy"] = (
    df_project["ceiling_fan_energy"]
    + df_project["lighting_energy"]
    + df_project["plug_load_energy"]
    + df_project["chilled_water_energy"]
    + df_project["fcu_fan_energy"]
)

hourly_energy = df_project.groupby("hour")["total_energy"].mean()

hourly_energy

plt.figure(figsize=(10, 5))

plt.plot(hourly_energy.index, hourly_energy.values, marker="o")

plt.xlabel("Hour of Day")
plt.ylabel("Average Energy Consumption")
plt.title("Average Building Energy Consumption by Hour")
plt.xticks(range(0, 24))
plt.grid(True)
plt.show()

peak_hour = hourly_energy.idxmax()
peak_energy = hourly_energy.max()

print("Peak energy hour:", peak_hour)
print("Average energy at peak:", peak_energy)

low_hour = hourly_energy.idxmin()
low_energy = hourly_energy.min()

print("Lowest energy hour:", low_hour)
print("Average energy at lowest:", low_energy)

low_hour = hourly_energy.idxmin()
low_energy = hourly_energy.min()

print("Lowest energy hour:", low_hour)
print("Average energy at lowest:", low_energy)

occupancy_energy = df_project.groupby("occupant_count")["total_energy"].mean()

print(occupancy_energy)

plt.figure(figsize=(10, 5))

plt.scatter(
    occupancy_energy.index,
    occupancy_energy.values
)

plt.xlabel("Number of Occupants")
plt.ylabel("Average Energy Consumption")
plt.title("Occupancy vs Building Energy Consumption")
plt.grid(True)
plt.show()

mean_energy = df_project["total_energy"].mean()
std_energy = df_project["total_energy"].std()

print("Average energy:", mean_energy)
print("Standard deviation:", std_energy)

df_project["z_score"] = (
    df_project["total_energy"] - mean_energy
) / std_energy

df_project[["timestamp", "total_energy", "z_score"]].head()

anomalies = df_project[df_project["z_score"] > 2]

print("Number of high-energy anomalies:", len(anomalies))

top_anomalies = anomalies.sort_values(
    "total_energy",
    ascending=False
).head(10)

top_anomalies[
    ["timestamp", "total_energy", "occupant_count", "air_temperature"]
]

top_event = df_project.loc[2418]

print("Timestamp:", top_event["timestamp"])
print("Total energy:", top_event["total_energy"])
print("Occupants:", top_event["occupant_count"])
print("Lighting energy:", top_event["lighting_energy"])
print("Plug load energy:", top_event["plug_load_energy"])
print("Chilled water energy:", top_event["chilled_water_energy"])
print("FCU fan energy:", top_event["fcu_fan_energy"])
print("Ceiling fan energy:", top_event["ceiling_fan_energy"])

chilled_water_share = (
    df_project["chilled_water_energy"].sum()
    / df_project["total_energy"].sum()
) * 100

print("Chilled water contribution to total energy:",
      chilled_water_share, "%")

df_project["date"] = df_project["timestamp"].dt.date

daily_energy = df_project.groupby("date")["total_energy"].sum()

print(daily_energy.sort_values(ascending=False).head(10))

plt.figure(figsize=(12, 5))

plt.plot(
    daily_energy.index,
    daily_energy.values,
    marker="o"
)

plt.xlabel("Date")
plt.ylabel("Total Energy Consumption")
plt.title("Daily Building Energy Consumption")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

temperature_energy = df_project[
    ["air_temperature", "total_energy"]
].corr()

print(temperature_energy)

cooling_temperature_corr = df_project[
    ["dry_bulb_temp", "chilled_water_energy"]
].corr()

print(cooling_temperature_corr)

correlation = df_project[
    [
        "occupant_count",
        "dry_bulb_temp",
        "outdoor_relative_humidity",
        "total_energy"
    ]
].corr()

print(correlation["total_energy"].sort_values(ascending=False))

features = [
    "occupant_count",
    "dry_bulb_temp",
    "outdoor_relative_humidity",
    "air_temperature",
    "indoor_relative_humidity",
    "indoor_co2",
    "illuminance"
]

X = df_project[features]
y = df_project["total_energy"]

print("Features:", X.shape)
print("Target:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training rows:", X_train.shape[0])
print("Testing rows:", X_test.shape[0])

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Model training completed!")

y_pred = model.predict(X_test)

print("Predictions generated:", len(y_pred))

from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("R² Score:", r2)

features = [
    "occupant_count",
    "dry_bulb_temp",
    "outdoor_relative_humidity",
    "air_temperature",
    "indoor_relative_humidity",
    "indoor_co2",
    "illuminance",
    "hour",
    "day_of_week",
    "month"
]

X = pd.get_dummies(
    df_project[features],
    columns=["day_of_week"],
    drop_first=True
)

y = df_project["total_energy"]

print("New feature shape:", X.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training rows:", X_train.shape[0])
print("Testing rows:", X_test.shape[0])

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Updated model training completed!")

from sklearn.metrics import mean_absolute_error, r2_score

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Updated Mean Absolute Error:", mae)
print("Updated R² Score:", r2)

feature_importance = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print(feature_importance)

plt.figure(figsize=(12, 5))

plt.plot(
    y_test.values[:200],
    label="Actual Energy"
)

plt.plot(
    y_pred[:200],
    label="Predicted Energy"
)

plt.xlabel("Test Data Points")
plt.ylabel("Energy Consumption")
plt.title("Actual vs Predicted Building Energy")
plt.legend()
plt.grid(True)
plt.show()

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Improved MAE:", mae)
print("Improved R²:", r2)

df_test = X_test.copy()

df_test["actual_energy"] = y_test.values
df_test["predicted_energy"] = y_pred

df_test["energy_difference"] = (
    df_test["actual_energy"] - df_test["predicted_energy"]
)

print(df_test[[
    "actual_energy",
    "predicted_energy",
    "energy_difference"
]].head())

error_std = df_test["energy_difference"].std()

df_test["anomaly"] = (
    df_test["energy_difference"] > 2 * error_std
)

print("Error standard deviation:", error_std)
print("Number of anomalies:", df_test["anomaly"].sum())

top_model_anomalies = df_test[
    df_test["anomaly"] == True
].sort_values(
    "energy_difference",
    ascending=False
).head(10)

print(
    top_model_anomalies[
        [
            "actual_energy",
            "predicted_energy",
            "energy_difference",
            "anomaly"
        ]
    ]
)

anomaly_index = 2718

print(df_project.loc[
    anomaly_index,
    [
        "timestamp",
        "total_energy",
        "occupant_count",
        "air_temperature",
        "indoor_relative_humidity",
        "indoor_co2",
        "lighting_energy",
        "plug_load_energy",
        "chilled_water_energy",
        "fcu_fan_energy",
        "ceiling_fan_energy"
    ]
])

anomalies_full = df_project.loc[
    df_test[df_test["anomaly"]].index
]

zero_occupancy_anomalies = (
    anomalies_full["occupant_count"] == 0
).sum()

print("Total model anomalies:", len(anomalies_full))
print("Anomalies with zero occupancy:", zero_occupancy_anomalies)

zero_occ_anomalies = anomalies_full[
    anomalies_full["occupant_count"] == 0
]

cooling_dominant = (
    zero_occ_anomalies["chilled_water_energy"]
    / zero_occ_anomalies["total_energy"]
    > 0.5
).sum()

print("Zero-occupancy anomalies:", len(zero_occ_anomalies))
print("Cooling-dominant anomalies:", cooling_dominant)

scenario = X_test.iloc[0].copy()

occupancy_values = [0, 5, 10, 20, 30, 40]

scenario_results = []

for occupants in occupancy_values:
    scenario["occupant_count"] = occupants

    predicted = model.predict(
        scenario.to_frame().T
    )[0]

    scenario_results.append(
        [occupants, predicted]
    )

scenario_results

scenario_df = pd.DataFrame(
    scenario_results,
    columns=["occupants", "predicted_energy"]
)

print(scenario_df)

plt.figure(figsize=(10, 5))

plt.plot(
    scenario_df["occupants"],
    scenario_df["predicted_energy"],
    marker="o"
)

plt.xlabel("Number of Occupants")
plt.ylabel("Predicted Energy Consumption")
plt.title("Digital Twin: Energy Scenario by Occupancy")
plt.grid(True)
plt.show()

energy_components = {
    "Ceiling Fan": df_project["ceiling_fan_energy"].sum(),
    "Lighting": df_project["lighting_energy"].sum(),
    "Plug Load": df_project["plug_load_energy"].sum(),
    "Chilled Water": df_project["chilled_water_energy"].sum(),
    "FCU Fan": df_project["fcu_fan_energy"].sum()
}

energy_components

energy_df = pd.DataFrame(
    list(energy_components.items()),
    columns=["component", "energy"]
)

plt.figure(figsize=(10, 5))

plt.bar(
    energy_df["component"],
    energy_df["energy"]
)

plt.xlabel("Energy Component")
plt.ylabel("Total Energy Consumption")
plt.title("Energy Consumption by Component")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

print("===== SMART BUILDING DIGITAL TWIN =====")

print("\nDataset:")
print("Rows:", len(df_project))

print("\nModel Performance:")
print("MAE:", round(mae, 4))
print("R² Score:", round(r2, 4))

print("\nAnomaly Detection:")
print("Total anomalies:", len(anomalies_full))
print("Zero-occupancy anomalies:", len(zero_occ_anomalies))
print("Cooling-dominant zero-occupancy anomalies:", cooling_dominant)

print("\nEnergy Analysis:")
print("Largest energy component:", max(
    energy_components,
    key=energy_components.get
))
print("Largest component consumption:",
      round(max(energy_components.values()), 2))

"""## Project Conclusion

The Smart Building Digital Twin analyzes real building data to understand energy consumption, identify unusual energy-use patterns, and simulate different occupancy scenarios.

### Key Findings

- Chilled water was the largest energy component.
- Occupancy and time of day were important predictors of energy consumption.
- 75 potential energy anomalies were detected.
- 45 anomalies occurred when the room had zero occupants.
- All zero-occupancy anomalies were cooling-dominant.
- The Random Forest model achieved an R-squared score of 0.4716 and an MAE of 0.3574.

The analysis demonstrates how Python and machine learning can support building energy monitoring, anomaly detection, and operational decision-making.

# Smart Building Digital Twin

## Project Overview

The Smart Building Digital Twin is a Python-based data analytics and machine learning project that analyzes real building data to understand energy consumption patterns, detect potential energy anomalies, and simulate energy usage under different occupancy scenarios.

The project uses real room-level building data and applies data cleaning, exploratory data analysis, feature engineering, machine learning, and anomaly detection techniques to generate actionable insights for building energy management.

## Dataset & Tools Used

### Dataset
ROBOD (Room-level Occupancy and Building Operation Dataset) from the National University of Singapore (NUS).

The dataset contains real building measurements collected at 5-minute intervals, including energy consumption, occupancy, indoor environmental conditions, and outdoor weather conditions.

### Tools & Technologies
- Python
- Pandas
- NumPy
- Matplotlib

## Project Methodology

The project follows these main steps:

1. Load and inspect the real building dataset.
2. Select relevant energy, occupancy, environmental, and weather variables.
3. Clean missing values and convert timestamps.
4. Create time-based features such as hour, day of week, and month.
5. Analyze energy consumption patterns and relationships between variables.
6. Detect unusual energy consumption using statistical and machine-learning approaches.
7. Build a Random Forest model to estimate expected energy consumption.
8. Compare actual and predicted energy consumption to identify potential anomalies.
9. Simulate different occupancy scenarios using the trained model.
10. Generate insights and recommendations for building energy management.

## Key Results

- 8,352 real building observations were analyzed.
- Chilled water was the largest energy component.
- Occupancy and hour of day were important predictors of energy consumption.
- 75 potential energy anomalies were detected.
- 45 of the detected anomalies occurred when the room had zero occupants.
- All 45 zero-occupancy anomalies were cooling-dominant.
- The Random Forest model achieved an R-squared score of 0.4716.
- The model achieved a Mean Absolute Error (MAE) of 0.3574.

## Data Source

The dataset used in this project is the ROBOD (Room-level Occupancy and Building Operation Dataset), developed by researchers at the National University of Singapore.

The data contains real measurements collected from a building environment, including occupancy, indoor conditions, outdoor weather, and energy end-use measurements.

This project uses data from Room 1 of the dataset.

## Business Insights & Recommendations

The analysis indicates that cooling-related energy consumption is a major contributor to the building's energy usage.

Several potential anomalies occurred during periods with zero recorded occupancy, and these events were dominated by chilled-water consumption. These patterns may indicate opportunities to review cooling-system schedules and operating conditions during unoccupied periods.

### Recommendations

- Review cooling-system operation during unoccupied periods.
- Investigate unusually high chilled-water consumption.
- Use occupancy patterns to improve HVAC scheduling.
- Monitor energy consumption continuously to identify unusual events.
- Use the predictive model as a baseline for identifying deviations from expected energy usage.
"""

